// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"prometheusdemo/handler"
	"prometheusdemo/ioc"
)

// Injectors from wire.go:

func InitWeb() *gin.Engine {
	v := ioc.InitMiddlewares()
	serverConfig := ioc.InitConfig()
	db := ioc.InitDB(serverConfig)
	userHandler := handler.NewUserHandler(db)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
