version: '3.0'
services:
  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise:10.2.0
    ports:
      - 3000:3000
  zipkin:
    image: openzipkin/zipkin-slim:2.24
    ports:
      - '9411:9411'